### ISSUE TITLE
`rustfmt` is broken

### ISSUE THREAD

**Issue by joske** [mason-org/mason-registry#2054]
Hi,

due to upstream changes, the binaries for `rustfmt` are now broken (they no longer work as standalone binary). See https://github.com/mason-org/mason-registry/pull/1434 for more information.

When I change the symlink in `~/.local/share/nvim/mason/bin/rustfmt` to point to my system `rustfmt`, code formatting works again.

Downloading the binaries from `rustfmt` project is not a viable option going forward.

**Comment by williamboman** [comment]
Hello! Yeah I opened an issue with them to learn more, it seems like `rustfmt` will need to be managed via `rustup` directly onwards due to changes upstream in rustc.

What this means right now is that the `rustfmt` package will have to be deprecated in Mason, and users must manage it externally (i.e. directly via `rustup component`). `rustup component` installs components in `~/.rustup` in the currently active toolchain. Changing Mason to refer to these would be out of scope and violate the principle of fully contained installations - the Mason installation would become "corrupt" should a user change toolchains or uninstall `rustfmt`.

**Comment by williamboman** [comment]
Package has been deprecated and downgraded to a functional version in #2059. Should the distribution alternatives change in the future, it will be "un-deprecated" again 😄
