### ISSUE TITLE
mojo lsp support

### ISSUE THREAD

**Issue by sangshuduo** [mason-org/mason-registry#2710]
I wish for more upvotes by more people who want to use Mason to install the Mojo language

**Comment by williamboman** [comment]
Hello! It seems like this package is hidden behind a paywall, I can't even find information about it without having to sign up at Modular. Packages supported by the core registry needs to be publicly available and ideally entirely open source.

**Comment by gsouf** [comment]
@williamboman  not sure which package or paywal you mentioned in your previous message, but things might have changed since then


On the link below they mention:

> Starting in v25.5, you can install a standalone mojo Conda package, which includes everything you need to write Mojo programs for CPUs and GPUs.

https://docs.modular.com/max/packages

I'm not very well informed of how things work in Mason and with LSP, so I can't tell, but maybe you can let us know if that helps moving forward with adding Mojo to Mason registry?
