### ISSUE TITLE
Update html lsp

### ISSUE THREAD

**Issue by ildar-shaymukhametov** [mason-org/mason-registry#6533]
---
name: html-lsp
Version 5.3.0 is available
Why are you not updating it?
Or maybe I can do it myself locally? How?
Will it work?

description: Language Server Protocol implementation for HTML.
homepage: https://github.com/microsoft/vscode-html-languageservice
licenses:
  - MIT
languages:
  - HTML
categories:
  - LSP

source:
  id: pkg:npm/vscode-langservers-extracted@4.10.0

schemas:
  lsp: vscode:https://raw.githubusercontent.com/microsoft/vscode/main/extensions/html-language-features/package.json

bin:
  vscode-html-language-server: npm:vscode-html-language-server

**Comment by OurCodeBase** [comment]
Hello **@ildar-shaymukhametov**

`html-lsp` is already updated to the latest version because of `html-lsp` is actually extracted from `vscode's html-lsp`. You can see the repository here [`hrsh7th/vscode-langservers-extracted`](https://github.com/hrsh7th/vscode-langservers-extracted).

So kindly close and reduce this issue.
